[versions]
agp = "8.13.2"
kotlin = "2.3.21"
zygoteloader = "bf5078e182"
r8_annotations = "v1.0.1"
androidx-annotation = "1.10.0"

[plugins]
agp-app = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-github-aerathstuff-zygoteloader = { id = "com.github.aerath-stuff.ZygoteLoader", version.ref = "zygoteloader" }

[libraries]
androidx-annotation-jvm = { module = "androidx.annotation:annotation-jvm", version.ref = "androidx-annotation" }
io-github-vova7878-r8annotations = { module = "io.github.vova7878:R8Annotations", version.ref = "r8_annotations" }
